modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/TropheusJ/stonecutter_groups"
license = "MIT"

[[mods]]
modId = "stonecutter_groups"
version = "${version}"
displayName = "Stonecutter Groups"
authors = "Tropheus Jay"
description = '''
More concise Stonecutter recipes.
'''
logoFile = "icon.png"

[[dependencies.stonecutter_groups]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
